---
version: 2
updates:
  # Gradle Dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:08"
    open-pull-requests-limit: 0
    versioning-strategy: "auto"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"