---
version: 2
updates:
  # Gradle Dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:24"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "chore"
      include: "scope"

